language: java
install: clean verify
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  keep_history: true
  local_dir: miniEclipse
  verbose: true
  on:
    branch: master