language: java
install: mvn -version
script:
- mvn clean verify
# - rm -Rf product/target/products/dev.saseno.eclipse.mini
- rm -Rf MiniEclipse/*
- mkdir out
- mkdir out/MiniEclipse
- cp README.md out/
- cp -v product/target/products/*.zip out/MiniEclipse
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCTOKEN
  keep_history: true
  local_dir: out
  verbose: true
  on:
    branch: master
    # repo: saseno/saseno.github.io