language: java
install: mvn -version
script:
- mvn clean verify
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCTOKEN
  keep_history: true
  local_dir: product/target/products
  verbose: true
  on:
    branch: master