language: java
install: mvn clean verify
deploy:
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_ACCTOKEN
  keep_history: true
  local_dir: miniEclipse
  verbose: true
  on:
    branch: master