name: Java CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Maven
      run: mvn clean verify --file pom.xml
    - name: upload artifact linux
      uses: actions/upload-artifact@v4
      with:
        name: MiniEclipse.gtk.x86_64.zip
        path: /home/runner/work/MiniEclipse/MiniEclipse/product/target/products/dev.saseno.eclipse.mini-linux.gtk.x86_64.zip
    - name: upload artifact win
      uses: actions/upload-artifact@v4
      with:
        name: MiniEclipse.win32.x86_64.zip
        path: /home/runner/work/MiniEclipse/MiniEclipse/product/target/products/dev.saseno.eclipse.mini-win32.win32.x86_64.zip        
    - name: upload artifact Mac
      uses: actions/upload-artifact@v4
      with:
        name: MiniEclipse.macosx.cocoa.x86_64.zip
        path: /home/runner/work/MiniEclipse/MiniEclipse/product/target/products/dev.saseno.eclipse.mini-macosx.cocoa.x86_64.zip
